### ISSUE TITLE
build task never exits

### ISSUE THREAD

**Issue by thadeetrompetter** [voorhoede/front-end-guide#32]
When running `gulp build` the process does not exit. This causes ci services to stall due to inactivity. travis eventually fails with a timeout, while jenkins hangs indefinitely. the `build_html` task appears to be the culprit. When this task is excluded, the build process does complete.

**Comment by jbmoelker** [comment]
I could imagine `plumber` is suppressing the actual errors. I believe we had the same issue with the `build_less` task. I do think `plumber` is handy during development, but not during the production build.  So perhaps we could make it conditional on watch:

``` js
// gulpfile.js
var isWatching = false;
// ...
function watchTask () {
  isWatching = true;
  // ...
}
// ...
function buildHtmlTask() {
  return srcFiles('html')
    .pipe(gulpif(isWatching, plumber()))
    .pipe(nunjucksRender( /* ... */))
    .pipe(gulpif(isWatching, plumber.stop()))
    // ...
}
```

**Comment by decrek** [comment]
This is because in the nunjucks update from 1.1.0 to 1.2.0 a dependency was added, i.e. `chokidar`. Now by default in the nunjucks render a watch configuration is set to true. So I'll add the watch property and set it to false. See also https://github.com/mozilla/nunjucks/issues/369
